#!/usr/bin/env python3
"""Generate code/COMPONENTS.md for a product repository built with the framework.

Run from the product repository root:  python3 <path-to>/components_index.py
Layout expected (framework convention): code/<system>/<component>/...
A tag is any occurrence of  @node <node-id>  in a file under a component
(comment syntax is up to the language; ids are kebab-case file stems from
logic/). The index lists component → system → nodes served, and flags:
components with no tag, files lying directly under a system folder (not in
a component), tags with no node file, and live nodes with no component.
It is the dev-side document. Never edit it by hand.
"""
import re
import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path.cwd()
CODE = ROOT / "code"
LOGIC = ROOT / "logic"
OUT = CODE / "COMPONENTS.md"
TAG = re.compile(r"@node\s+([a-z0-9]+(?:-[a-z0-9]+)*)(?![\w./-])")
BAD_TAG = re.compile(r"@node\s+(\S+)")
SKIP_DIRS = {"node_modules", ".git", "dist", "build", "__pycache__", ".venv"}


def main() -> int:
    if not CODE.exists():
        print("no code/ folder here; run from the product repository root")
        return 1
    comps = defaultdict(set)  # (system, component) -> node ids
    loose = []  # files directly under a system folder, outside any component
    malformed = []  # @node tags that are not a kebab-case id
    for system in sorted(p for p in CODE.iterdir() if p.is_dir() and not p.name.startswith(".")):
        for f in system.iterdir():
            if f.is_file() and f.name != "COMPONENTS.md":
                loose.append(str(f.relative_to(CODE)))
        for comp in sorted(p for p in system.iterdir() if p.is_dir() and not p.name.startswith(".")):
            comps[(system.name, comp.name)]  # register even if untagged
            for f in comp.rglob("*"):
                if f.is_file() and not any(part in SKIP_DIRS for part in f.parts):
                    try:
                        text = f.read_text(encoding="utf-8", errors="ignore")
                        good = {m.group(1) for m in TAG.finditer(text)}
                        comps[(system.name, comp.name)].update(good)
                        for m in BAD_TAG.finditer(text):
                            if m.group(1) not in good:
                                malformed.append(f"`{m.group(1)}` in {f.relative_to(CODE)}")
                    except OSError:
                        pass
    known_nodes, retired = set(), set()
    if LOGIC.exists():
        node_files = [p for p in LOGIC.rglob("*.md") if p.name not in ("INDEX.md", "README.md")]
        retired_dirs = set()
        for p in sorted(node_files, key=lambda x: len(x.parts)):
            known_nodes.add(p.stem)
            rel = str(p.relative_to(LOGIC).with_suffix(""))
            own = re.search(r"^Status:\s*retired\b", p.read_text(encoding="utf-8", errors="ignore"), re.M)
            if own or any(rel.startswith(d + "/") for d in retired_dirs):
                retired.add(p.stem)
                retired_dirs.add(rel)
    served = set().union(*comps.values()) if comps else set()

    lines = ["# Components", "", "Generated by framework/tools/components_index.py. Do not edit by hand.",
             "component → system → nodes served (tags `@node <id>`).", ""]
    cur = None
    for (system, comp), nodes in sorted(comps.items()):
        if system != cur:
            lines += ["", f"## {system}", ""] if cur else [f"## {system}", ""]
            cur = system
        tags = ", ".join(f"`{n}`" for n in sorted(nodes)) if nodes else "**untagged — finding**"
        lines.append(f"- `{comp}` → {tags}")
    unknown = sorted(served - known_nodes) if known_nodes else []
    unserved = sorted(known_nodes - served - retired) if known_nodes else []
    if loose:
        lines += ["", "## Files outside any component (finding)", ""] + [f"- `{f}`" for f in loose]
    if malformed:
        lines += ["", "## Malformed tags (finding)", ""] + [f"- {m}" for m in malformed]
    dead = sorted(f"`{c}` ({s})" for (s, c), nodes in comps.items() if nodes and nodes <= retired)
    if dead:
        lines += ["", "## Components served only by retired nodes — remove at the next delivery (finding)", ""] + [f"- {d}" for d in dead]
    if unknown:
        lines += ["", "## Tags with no node file (finding)", ""] + [f"- `{n}`" for n in unknown]
    if unserved:
        lines += ["", "## Nodes with no component yet", ""] + [f"- `{n}`" for n in unserved]
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)} ({len(comps)} components)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
