#!/usr/bin/env python3
"""Generate logic/INDEX.md for a product repository built with the framework.

Run from the product repository root:  python3 <path-to>/logic_index.py
Reads every logic/**/*.md node file (README.md and INDEX.md are ignored).
A node's id is its file stem (kebab-case, unique across the tree); the
folders are its placement and may change without changing the id. A node
file is Markdown whose first line is "# <title>", with a "## Acceptance
criteria" section (one criterion per line) and, optionally, a line
"Status: retired <date>". Duplicate stems are reported as a finding.
The index is the knowledge-transfer document: the tree, one line per node,
with its criteria (= the built use cases). Never edit it by hand.
"""
import re
import sys
from pathlib import Path

ROOT = Path.cwd()
LOGIC = ROOT / "logic"
OUT = LOGIC / "INDEX.md"


def parse(path: Path):
    text = path.read_text(encoding="utf-8")
    title = next((l[2:].strip() for l in text.splitlines() if l.startswith("# ")), path.stem)
    status = re.search(r"^Status:\s*(.+)$", text, re.M)
    retired = status if status and status.group(1).strip().lower().startswith("retired") else None
    crit = []
    m = re.search(r"^## Acceptance criteria\s*$(.*?)(?=^## |\Z)", text, re.M | re.S)
    if m:
        crit = [re.sub(r"^\s*[-*]\s+", "", l).strip() for l in m.group(1).splitlines() if re.sub(r"^\s*[-*]\s+", "", l).strip()]
    return title, (status.group(1).strip() if status else None), (retired is not None), crit


def main() -> int:
    if not LOGIC.exists():
        print("no logic/ folder here; run from the product repository root")
        return 1
    def key(p):  # parent node (login.md) before its children (login/…)
        rel = p.relative_to(LOGIC).with_suffix("")
        return tuple(rel.parts[:-1]) + (rel.parts[-1], "")
    files = sorted((p for p in LOGIC.rglob("*.md") if p.name not in ("INDEX.md", "README.md")), key=key)
    seen = {}
    lines = ["# Logic tree", "", "Generated by framework/tools/logic_index.py. Do not edit by hand.",
             "One line per node, nested as in the folders, with its status; criteria are use cases (built only when the status says delivered).", ""]
    printed_folders = set()
    retired_dirs: set = set()  # folders whose parent node is retired: children inherit it
    for p in files:
        rel = p.relative_to(LOGIC)
        node_id = p.stem
        depth = len(rel.parts) - 1
        inherited = any(str(rel).startswith(d + "/") for d in retired_dirs)
        # a folder with no node file of its own is shown as a plain heading so nothing floats
        for d in range(1, depth + 1):
            folder = Path(*rel.parts[:d])
            if folder not in printed_folders and not (LOGIC / folder).with_suffix(".md").exists():
                lines.append(f"{'  ' * (d - 1)}- *{folder.name}/* (folder, no node of its own)")
            printed_folders.add(folder)
        title, status, retired, crit = parse(p)
        if retired:
            retired_dirs.add(str(rel.with_suffix("")))
        if inherited and not retired:
            status = "retired with parent"
        flag = f" — {status}" if status else " — **no Status line (finding)**"
        dup = f" — **duplicate id, also at {seen[node_id]}**" if node_id in seen else ""
        seen.setdefault(node_id, str(rel))
        lines.append(f"{'  ' * depth}- **{title}** `{node_id}`{flag}{dup}")
        for c in crit:
            lines.append(f"{'  ' * (depth + 1)}- · {c}")
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)} ({len(files)} nodes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
